In [43]:
import glob
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [44]:
import os
print(os.getcwd())

C:\Users\dyan\final-berkeley-project

In [46]:
data = pd.read_csv('recruiting_cleandata_pac12.csv')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

In [28]:
data.shape

(59061, 11)

In [29]:
df = pd.DataFrame(data)

In [30]:
df.shape

(59061, 11)

In [41]:
df

,Unnamed: 0,ranking,name,highSchool,position,height,weight,stars,rating,college,year
0,0,1,D.J. Williams,"De La Salle (Concord, CA)",ILB,02-Jun,235,5.0,0.9998,Miami,2000
1,1,109,Stephen Williams,"Bolingbrook (Bolingbrook, IL)",SDE,03-Jun,275,4.0,0.9627,Indiana,2000
2,2,2,Brock Berlin,"Evangel Christian Academy (Shreveport, LA)",PRO,02-Jun,190,5.0,0.9998,Florida,2000
3,3,120,Nautyn McKay-Loescher,"Toronto (Toronto, OH)",WDE,04-Jun,240,4.0,0.9347,Alabama,2000
4,4,119,Marcus White,"Theodore (Theodore, AL)",SDE,05-Jun,270,4.0,0.9602,Auburn,2000
5,5,118,Dustin Picciotti,"Central Bucks West (Doylestown, PA)",FB,03-Jun,235,4.0,0.9602,Pittsburgh,2000
6,6,117,Lynn McGruder,"Cheyenne (North Las Vegas, NV)",DT,03-Jun,285,4.0,0.9606,Tennessee,2000
7,7,116,Jason Witten,"Elizabethton (Elizabethton, TN)",WDE,07-Jun,265,4.0,0.9606,Tennessee,2000
8,8,115,Doug Buckles,"Madison Central (Madison, MS)",OG,05-Jun,275,4.0,0.961,Ole Miss,2000
9,9,114,Cameron Wake,"DeMatha Catholic (Hyattsville, MD)",WDE,03-Jun,258,4.0,0.961,Penn State,2000
10,10,113,Jason Peters,"Queen City (Queen City, TX)",WDE,05-Jun,270,4.0,0.9614,Arkansas,2000
11,11,112,Maurice Mitchell,"Dougherty Comprehensive (Albany, GA)",OT,07-Jun,290,4.0,0.9614,Alabama,2000
12,12,111,Tatum Bell,"DeSoto (DeSoto, TX)",RB,11-May,190,4.0,0.9618,Oklahoma State,2000
13,13,63,Chris Boggas,"Irving (Irving, TX)",OT,05-Jun,310,4.0,0.9763,Kansas State,2000
14,14,110,John Rattay,"Desert Vista (Phoenix, AZ)",PRO,04-Jun,215,4.0,0.9622,Tennessee,2000
15,15,94,Brandon Sumner,"Mainland (Daytona Beach, FL)",PRO,05-Jun,220,4.0,0.9667,Georgia Tech,2000
16,16,107,Ronnie Brown,"Cartersville (Cartersville, GA)",RB,01-Jun,200,4.0,0.9631,Auburn,2000
17,17,106,Chris Young,"South Panola (Batesville, MS)",WR,02-Jun,184,4.0,0.9639,Vanderbilt,2000
18,18,105,Robert Peace,"Ruston (Ruston, LA)",ILB,03-Jun,215,4.0,0.9643,Tennessee,2000
19,19,104,Chris Kelley,"Seneca Valley (Germantown, MD)",PRO,02-Jun,205,4.0,0.9647,Maryland,2000
20,20,103,Willie Green,"Osceola (Kissimmee, FL)",RB,09-May,205,4.0,0.9647,Florida,2000
21,21,102,Ben Emanuel,"Clear Brook (Friendswood, TX)",S,02-Jun,190,4.0,0.9651,UCLA,2000
22,22,101,Bennie Mills,"Archbishop Rummel (Metairie, LA)",DT,04-Jun,280,4.0,0.9655,Florida,2000
23,23,100,Sean McHugh,"Chagrin Falls (Chagrin Falls, OH)",TE,06-Jun,245,4.0,0.9655,Penn State,2000
24,24,99,Alex Barron,"Orangeburg-Wilkinson (Orangeburg, SC)",OT,08-Jun,297,4.0,0.9657,Florida State,2000
25,25,97,Derron Parquet,"Archbishop Rummel (Metairie, LA)",RB,Jun-00,205,4.0,0.9659,LSU,2000
26,26,96,Mike Goolsby,"Joliet Catholic Academy (Joliet, IL)",ILB,04-Jun,225,4.0,0.9663,Notre Dame,2000
27,27,108,Richard Johnson,"Milford Mill Academy (Gwynn Oak, MD)",WR,Jun-00,170,4.0,0.9629,Virginia Tech,2000
28,28,93,Andrew Walter,"Grand Junction (Grand Junction, CO)",PRO,05-Jun,205,4.0,0.9671,Arizona State,2000
29,29,91,Kelvin Kight,"Lithonia (Lithonia, GA)",WR,Jun-00,185,4.0,0.9679,Florida,2000
...,...,...,...,...,...,...,...,...,...,...,...
59031,59031,105,Bram Walden,Saguaro (Scottsdale\t AZ),OT,04-Jun,270,3.0,0.85,uncommitted,2021
59032,59032,106,Jaden Genova,J Serra Catholic (San Juan Capistrano\t CA),OLB,Jun-00,200,3.0,0.82,uncommitted,2021
59033,59033,107,Jeffrey Bassa,Kearns (Salt Lake City\t UT),S,01-Jun,190,3.0,0.8,uncommitted,2021
59034,59034,81,Quenton Barnes,Cane Ridge (Antioch\t TN),WR,02-Jun,175,4.0,0.9679,uncommitted,2021
59035,59035,1,J.T. Tuimoloau,Eastside Catholic (Sammamish\t WA),DT,6-4.5,277,5.0,1,uncommitted,2021
59036,59036,17,Katron Evans,Granby (Norfolk\t VA),DT,04-Jun,265,5.0,0.9936,uncommitted,2021
59037,59037,18,Micah Morris,Camden County (Kingsland\t GA),OT,6-3.5,286,5.0,0.9932,uncommitted,2021
59038,59038,19,Payton Page,Dudley (Greensboro\t NC),DT,04-Jun,315,5.0,0.9928,uncommitted,2021
59039,59039,20,Troy Franklin,Menlo-Atherton (Menlo Park\t CA),WR,02-Jun,170,5.0,0.9924,uncommitted,2021
59040,59040,36,Will Shipley,Weddington (Matthews\t NC),APB,11-May,193,5.0,0.986,uncommitted,2021
59041,59041,35,Corey Collier,Miami Palmetto (Miami\t FL),CB,02-Jun,170,5.0,0.9864,uncommitted,2021
59042,59042,34,Brayden Wood,Fairview (Boulder\t CO),WDE,03-Jun,250,5.0,0.9868,uncommitted,2021
59043,59043,33,Zeiqui Lawton,South Charleston (Charleston\t WV),SDE,02-Jun,226,5.0,0.9872,uncommitted,2021
59044,59044,32,Shadrach Banks,North Shore (Houston\t TX),ATH,Jun-00,200,5.0,0.9876,uncommitted,2021
59045,59045,31,Terrence Ferguson,Peach County (Fort Valley\t GA),OT,04-Jun,270,5.0,0.988,uncommitted,2021
59046,59046,3,Jack Sawyer,Pickerington North (Pickerington\t OH),SDE,05-Jun,219,5.0,0.9992,uncommitted,2021
59047,59047,30,Ga'Quincy McKinstry,Pinson Valley (Pinson\t AL),CB,01-Jun,175,5.0,0.9884,uncommitted,2021
59048,59048,28,A.J. Kirk,Dublin Coffman (Columbus\t OH),S,Jun-00,200,5.0,0.9892,uncommitted,2021
59049,59049,27,Hayden Conner,Taylor (Katy\t TX),OT,6-5.5,298,5.0,0.9896,uncommitted,2021
59050,59050,26,Damon Payne,Belleville (Belleville\t MI),OG,04-Jun,255,5.0,0.99,uncommitted,2021
59051,59051,25,Reuben Fatheree,Foster (Richmond\t TX),OT,08-Jun,300,5.0,0.9904,uncommitted,2021
59052,59052,24,Dominic Bass,Phillips Academy (Chicago\t IL),DT,04-Jun,250,5.0,0.9908,uncommitted,2021
59053,59053,22,Donovan Jackson,Episcopal (Bellaire\t TX),OT,6-3.5,305,5.0,0.9916,uncommitted,2021
59054,59054,21,Ma'a Gaoteote,Faith Lutheran (Las Vegas\t NV),OLB,02-Jun,220,5.0,0.992,USC,2021
59055,59055,78,Jaylen Anderson,Perry (Perry\t OH),RB,01-Jun,210,4.0,0.9691,uncommitted,2021
59056,59056,45,Julien Simon,Lincoln (Tacoma\t WA),ATH,02-Jun,221,4.0,0.9824,uncommitted,2021
59057,59057,80,Eli Sutton,Brentwood Academy (Brentwood\t TN),OT,06-Jun,265,4.0,0.9683,uncommitted,2021
59058,59058,95,Deion Colzie,Athens Academy (Athens\t GA),WR,04-Jun,180,4.0,0.9623,uncommitted,2021
59059,59059,29,Bryce Foster,Taylor (Katy\t TX),OT,05-Jun,315,5.0,0.9888,uncommitted,2021
59060,59060,23,Kendrick Blackshire,Horn (Mesquite\t TX),ILB,02-Jun,250,5.0,0.9912,uncommitted,2021

In [ ]:
dfdropped = df.dropp

In [36]:
df.groupby(['college', 'year', 'stars']).count()

                              Unnamed: 0  ranking  name  highSchool  position  \
college           year stars
Abilene Christian 2013 3.0             1        1     1           1         1
                  2014 2.0             3        3     3           3         3
                       3.0             2        2     2           2         2
                  2015 2.0             1        1     1           1         1
                       3.0             1        1     1           1         1
                  2016 2.0             6        6     6           6         6
                       3.0             2        2     2           2         2
                  2017 2.0             3        3     3           3         3
Air Force         2002 2.0             1        1     1           1         1
                  2003 2.0             2        2     2           2         2
                  2004 2.0             4        4     4           4         4
                  2005 1.0             4        4     4           4         4
                       2.0             7        7     7           7         7
                       3.0             1        1     1           1         1
                  2006 1.0             3        3     3           3         3
                       2.0            10       10    10          10        10
                  2007 1.0             2        2     2           2         2
                       2.0             6        6     6           6         6
                  2008 2.0             4        4     4           4         4
                  2009 1.0             4        4     4           4         4
                       2.0            15       15    15          15        15
                       3.0             1        1     1           1         1
                  2010 2.0             1        1     1           1         1
                       3.0             1        1     1           1         1
                  2012 1.0             2        2     2           2         2
                       2.0            27       27    27          27        27
                       3.0             8        8     8           8         8
                  2013 1.0             1        1     1           1         1
                       2.0            33       33    33          33        33
                       3.0             4        4     4           4         4
...                                  ...      ...   ...         ...       ...
uncommitted       2014 3.0           153      153   153         153       153
                       4.0             4        4     4           4         4
                  2015 1.0            15       15    15          15        15
                       2.0           221      221   221         221       221
                       3.0           195      195   195         195       195
                       4.0             4        4     4           4         4
                  2016 1.0             6        6     6           6         6
                       2.0           297      297   297         297       297
                       3.0           221      221   221         221       221
                       4.0             2        2     2           2         2
                  2017 1.0             1        1     1           1         1
                       2.0           743      743   735         743       743
                       3.0           269      269   262         269       269
                       4.0             2        2     2           2         2
                  2018 1.0            91       91    91          91        91
                       2.0           544      544   544         544       544
                       3.0           251      251   251         251       251
                       4.0             1        1     1           1         1
                  2019 0.0            92        0     0           0         0
                       1.0            22        0    22          22        22
                       2.0           658       37   658         658       658
                       3.0           470       86   470         470       470
                       4.0             2        2     2           2         2
                  2020 2.0            38        0    38          38        38
                       3.0           711      596   711         711       711
                       4.0           234      234   234         234       234
                       5.0            26       26    26          26        26
                  2021 3.0             6        6     6           6         6
                       4.0            54       54    54          54        54
                       5.0            37       37    37          37        37

                              height  weight  rating
college           year stars
Abilene Christian 2013 3.0         1       1       1
                  2014 2.0         3       3       3
                       3.0         2       2       2
                  2015 2.0         1       1       1
                       3.0         1       1       1
                  2016 2.0         6       6       6
                       3.0         2       2       2
                  2017 2.0         3       3       3
Air Force         2002 2.0         1       1       1
                  2003 2.0         2       2       2
                  2004 2.0         4       4       4
                  2005 1.0         4       4       4
                       2.0         7       7       7
                       3.0         1       1       1
                  2006 1.0         3       3       3
                       2.0        10      10      10
                  2007 1.0         2       2       2
                       2.0         6       6       6
                  2008 2.0         4       4       4
                  2009 1.0         4       4       4
                       2.0        15      15      15
                       3.0         1       1       1
                  2010 2.0         1       1       1
                       3.0         1       1       1
                  2012 1.0         2       2       2
                       2.0        27      27      27
                       3.0         8       8       8
                  2013 1.0         1       1       1
                       2.0        33      33      33
                       3.0         4       4       4
...                              ...     ...     ...
uncommitted       2014 3.0       153     153     153
                       4.0         4       4       4
                  2015 1.0        15      15      15
                       2.0       221     221     221
                       3.0       195     195     195
                       4.0         4       4       4
                  2016 1.0         6       6       6
                       2.0       297     297     297
                       3.0       221     221     221
                       4.0         2       2       2
                  2017 1.0         1       1       1
                       2.0       743     743     743
                       3.0       269     269     269
                       4.0         2       2       2
                  2018 1.0        91      91      91
                       2.0       544     544     544
                       3.0       251     251     251
                       4.0         1       1       1
                  2019 0.0         0       0       0
                       1.0        22      22      22
                       2.0       658     658     658
                       3.0       470     470     470
                       4.0         2       2       2
                  2020 2.0        38      38      38
                       3.0       711     711     711
                       4.0       234     234     234
                       5.0        26      26      26
                  2021 3.0         6       6       6
                       4.0        54      54      54
                       5.0        37      37      37

[7388 rows x 8 columns]